require: rubocop-rails

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/20210505000040_acts_as_taggable_on_migration.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20210505000041_add_missing_unique_indices.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20210505000042_add_taggings_counter_cache_to_tags.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20210505000043_add_missing_taggable_index.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20210505000044_change_collation_for_tag_names.acts_as_taggable_on_engine.rb'
    - 'db/migrate/20210505000045_add_missing_indexes_on_taggings.acts_as_taggable_on_engine.rb'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.5

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 112  # Maximum line length from `rails new`

Rails:
  Enabled: true

Rails/SkipsModelValidations:
  Whitelist:
    - touch
    - toggle
    - toggle!

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
